### ISSUE TITLE
What's the significance of the commented line in OrderController?

### ISSUE THREAD

**Issue by kertnik05** [kertnik05/e-commerce#19]
https://github.com/kertnik05/e-commerce/blob/797af32c3a513d814b2b4e24f5da3ba104b62e2a/backend/app/Http/Controllers/OrderController.php#L17

**Comment by zxcjhaycee** [comment]
That line was for my testing purposes for the relationship. I forget to remove it before i commited/push my code.

**Comment by zxcjhaycee** [comment]
Why it is have an invalid tag?

**Comment by kertnik05** [comment]
Because the commented line doesn't feel right

**Comment by kertnik05** [comment]
Anyway, I'll just remove the invalid tag because the question tag feels more the appropriate tag

**Comment by zxcjhaycee** [comment]
Btw, i will remove the commented line nalang.

**Comment by kertnik05** [comment]
https://github.com/kertnik05/e-commerce/blob/f03861592cf76de8c275c62c10d3385e43f37031/backend/app/Http/Controllers/OrderController.php#L14
also remove this line
